from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
 
from db_declare import Supplier, Base


engine = create_engine('sqlite:///ke.db')
# Bind the engine to the metadata of the Base class so that the
# declaratives can be accessed through a DBSession instance
Base.metadata.bind = engine
 
DBSession = sessionmaker(bind=engine)
# A DBSession() instance establishes all conversations with the database
# and represents a "staging zone" for all the objects loaded into the
# database session object. Any change made against the objects in the
# session won't be persisted into the database until you call
# session.commit(). If you're not happy about the changes, you can
# revert all of them back to the last commit by calling
# session.rollback()
session = DBSession()

supplier1 = Supplier(name="A Associates", unit_measure="200", cost_unit_per_day="228", discipline="Food", location="Amsterdam", times_hired="0", url="http://outequivocating.com", contact="Camille Hardy", phone="+31-995-35-45-18", email="vel@vitaeposuereat.edu")
session.add(supplier1)
supplier2 = Supplier(name="Ac Metus Vitae Institute", unit_measure="180", cost_unit_per_day="247", discipline="Food", location="Amsterdam", times_hired="0", url="http://haaf.com", contact="Adara Patterson", phone="+31-931-42-01-36", email="mauris.ut@quam.org")
session.add(supplier2)
supplier3 = Supplier(name="Ac Turpis Industries", unit_measure="500", cost_unit_per_day="322", discipline="Tents", location="Amsterdam", times_hired="0", url="http://kiss.com", contact="Wyatt Russo", phone="+31-686-08-19-87", email="tempus.risus@dictum.org")
session.add(supplier3)
supplier4 = Supplier(name="Aenean Consulting", unit_measure="150", cost_unit_per_day="302", discipline="Food", location="Doetinchem", times_hired="0", url="http://bardy.com", contact="Hadley Howard", phone="+31-807-99-67-38", email="ridiculus.mus.Proin@pede.org")
session.add(supplier4)
supplier5 = Supplier(name="Aliquet Diam Sed Inc.", unit_measure="650", cost_unit_per_day="264", discipline="First Aid", location="Hoorn", times_hired="0", url="http://globally.com", contact="Joy Mayo", phone="+31-076-14-96-46", email="porttitor@vulputaterisusa.org")
session.add(supplier5)
supplier6 = Supplier(name="Aliquet Lobortis Inc.", unit_measure="500", cost_unit_per_day="192", discipline="Producer", location="Amsterdam", times_hired="15", experience_rating="4", quality_rating="4", price_rating="4", url="http://paralytic.com", contact="Haley Sexton", phone="+31-643-72-69-20", email="justo.sit.amet@tempusscelerisquelorem.co.uk")
session.add(supplier6)
supplier7 = Supplier(name="Amet Nulla Donec Incorporated", unit_measure="125", cost_unit_per_day="206", discipline="Cash register", location="Amersfoort", times_hired="0", url="http://soundtrack.com", contact="Uriah Gonzalez", phone="+31-225-18-77-11", email="arcu.Nunc.mauris@dolorsit.ca")
session.add(supplier7)
supplier8 = Supplier(name="Amet Ultricies Incorporated", unit_measure="450", cost_unit_per_day="327", discipline="Tents", location="Breda", times_hired="0", url="http://cutey.com", contact="Diana Barr", phone="+31-387-12-88-40", email="eget.volutpat@auguemalesuada.edu")
session.add(supplier8)
supplier9 = Supplier(name="Ante Vivamus Corporation", unit_measure="500", cost_unit_per_day="230", discipline="Stage manager", location="Amsterdam", times_hired="0", url="http://frondescence.com", contact="Dorian Bonner", phone="+31-337-36-39-85", email="consectetuer@Suspendisse.org")
session.add(supplier9)
supplier10 = Supplier(name="Arcu Vel Ltd", unit_measure="150", cost_unit_per_day="205", discipline="Cash register", location="Amsterdam", times_hired="6", experience_rating="5", quality_rating="5", price_rating="5", url="http://lasher.com", contact="Mia Evans", phone="+31-861-84-57-99", email="Suspendisse.ac.metus@pedePraesenteu.net")
session.add(supplier10)
supplier11 = Supplier(name="At Fringilla Purus Institute", unit_measure="175", cost_unit_per_day="295", discipline="Cash register", location="Rotterdam", times_hired="4", experience_rating="5", quality_rating="5", price_rating="5", url="http://sketch.com", contact="Camille Gordon", phone="+31-773-02-57-71", email="nunc.nulla@Donecporttitor.org")
session.add(supplier11)
supplier12 = Supplier(name="At Libero Industries", unit_measure="75", cost_unit_per_day="225", discipline="Cash register", location="Zaandam", times_hired="22", experience_rating="5", quality_rating="5", price_rating="5", url="http://narcosis.com", contact="Alexandra Woodard", phone="+31-044-62-01-75", email="risus.odio@diam.co.uk")
session.add(supplier12)
supplier13 = Supplier(name="At Nisi Corp.", unit_measure="100", cost_unit_per_day="285", discipline="Sitecrew", location="Amsterdam", times_hired="9", experience_rating="4", quality_rating="5", price_rating="5", url="http://plaided.com", contact="Lani Chavez", phone="+31-077-20-48-95", email="Phasellus.ornare.Fusce@perconubianostra.co.uk")
session.add(supplier13)
supplier14 = Supplier(name="At Pretium Aliquet Corp.", unit_measure="200", cost_unit_per_day="259", discipline="Plumbing", location="Maastricht", times_hired="0", url="http://uncorroded.com", contact="Amelia Medina", phone="+31-673-64-79-90", email="purus@eleifendvitaeerat.co.uk")
session.add(supplier14)
supplier15 = Supplier(name="Auctor Mauris Vel Foundation", unit_measure="120", cost_unit_per_day="269", discipline="Sitecrew", location="Amsterdam", times_hired="1", experience_rating="5", quality_rating="5", price_rating="3", url="http://powerful.com", contact="Kamal Franklin", phone="+31-918-48-26-12", email="Mauris.vestibulum@Quisque.co.uk")
session.add(supplier15)
supplier16 = Supplier(name="Auctor Non Feugiat Foundation", unit_measure="200", cost_unit_per_day="181", discipline="Fencing", location="Amsterdam", times_hired="11", url="http://accelerando.com", contact="Quon Levy", phone="+31-957-48-08-55", email="et.arcu.imperdiet@felisNulla.co.uk")
session.add(supplier16)
supplier17 = Supplier(name="Commodo Company", unit_measure="150", cost_unit_per_day="172", discipline="Extinguishers", location="Amersfoort", times_hired="0", url="http://random.com", contact="Rama Clay", phone="+31-244-17-81-43", email="tempus.lorem@aliquam.org")
session.add(supplier17)
supplier18 = Supplier(name="Commodo Limited", unit_measure="120", cost_unit_per_day="184", discipline="Food", location="Amsterdam", times_hired="0", url="http://underissue.com", contact="Ryan Wilkins", phone="+31-405-40-34-69", email="imperdiet.nec.leo@urnajusto.ca")
session.add(supplier18)
supplier19 = Supplier(name="Consequat Dolor Consulting", unit_measure="600", cost_unit_per_day="215", discipline="Tents", location="Mook", times_hired="0", url="http://arrhephoria.com", contact="Emi Mack", phone="+31-530-88-77-26", email="sem.consequat@dapibusgravidaAliquam.edu")
session.add(supplier19)
supplier20 = Supplier(name="Consequat Limited", unit_measure="150", cost_unit_per_day="282", discipline="Sitecrew", location="Rotterdam", times_hired="3", experience_rating="5", quality_rating="5", price_rating="3", url="http://valparaiso.com", contact="Camilla Valencia", phone="+31-595-08-57-78", email="id.ante.Nunc@viverraMaecenasiaculis.org")
session.add(supplier20)
supplier21 = Supplier(name="Consequat Nec Mollis LLP", unit_measure="50", cost_unit_per_day="325", discipline="Cash register", location="Achterveld", times_hired="8", experience_rating="5", quality_rating="5", price_rating="5", url="http://endometrial.com", contact="Martina Black", phone="+31-762-43-18-36", email="blandit.at@ipsumSuspendisse.edu")
session.add(supplier21)
supplier22 = Supplier(name="Conubia Nostra Per Inc.", unit_measure="100", cost_unit_per_day="290", discipline="Radios", location="Ermelo", times_hired="25", experience_rating="5", quality_rating="5", price_rating="3", url="http://quit.com", contact="Isabelle Russell", phone="+31-564-92-86-95", email="facilisis@dolorsit.co.uk")
session.add(supplier22)
supplier23 = Supplier(name="Cras Sed Leo Corporation", unit_measure="200", cost_unit_per_day="251", discipline="Cleaning", location="Houten", times_hired="0", url="http://zebraic.com", contact="Kane Eaton", phone="+31-162-66-73-26", email="condimentum.eget.volutpat@cursusluctus.ca")
session.add(supplier23)
supplier24 = Supplier(name="Cursus Nunc Mauris Company", unit_measure="100", cost_unit_per_day="230", discipline="Food", location="Ijmuiden", times_hired="0", url="http://protopathic.com", contact="Fay Mckinney", phone="+31-342-99-39-16", email="mollis.lectus@Vivamus.co.uk")
session.add(supplier24)
supplier25 = Supplier(name="Dictum Institute", unit_measure="250", cost_unit_per_day="288", discipline="Food", location="Amsterdam", times_hired="0", url="http://telferage.com", contact="Iris Mclaughlin", phone="+31-962-77-01-45", email="erat.volutpat@egetodioAliquam.co.uk")
session.add(supplier25)
supplier26 = Supplier(name="Dignissim Consulting", unit_measure="400", cost_unit_per_day="285", discipline="Casino", location="Hengelo", times_hired="0", url="http://buccaro.com", contact="Carla Campbell", phone="+31-063-06-56-11", email="faucibus.orci.luctus@euismodet.co.uk")
session.add(supplier26)
supplier27 = Supplier(name="Dignissim Corp.", unit_measure="75", cost_unit_per_day="313", discipline="Refrigerated container", location="Ijmuiden", times_hired="0", url="http://diluent.com", contact="Madeline Shaffer", phone="+31-324-90-17-33", email="laoreet@sollicitudinamalesuada.co.uk")
session.add(supplier27)
supplier28 = Supplier(name="Dignissim Lacus Aliquam Corp.", unit_measure="185", cost_unit_per_day="186", discipline="Office", location="Nijmegen", times_hired="5", experience_rating="2", quality_rating="2", price_rating="5", url="http://blessedly.com", contact="Joan Ratliff", phone="+31-529-87-35-64", email="hendrerit.a@diamDuis.net")
session.add(supplier28)
supplier29 = Supplier(name="Dignissim Magna A Limited", unit_measure="150", cost_unit_per_day="316", discipline="Light", location="Amsterdam", times_hired="0", url="http://uncontortive.com", contact="Ian House", phone="+31-240-29-98-75", email="lacus.Nulla@elitCurabitur.ca")
session.add(supplier29)
supplier30 = Supplier(name="Dolor Nonummy Ltd", unit_measure="275", cost_unit_per_day="308", discipline="Food", location="Almere", times_hired="0", url="http://prearrest.com", contact="Joel Delacruz", phone="+31-816-55-84-79", email="amet@neque.edu")
session.add(supplier30)
supplier31 = Supplier(name="Dolor Sit LLP", unit_measure="200", cost_unit_per_day="313", discipline="Sitecrew", location="Amsterdam", times_hired="9", experience_rating="4", quality_rating="5", price_rating="5", url="http://allantoic.com", contact="Jane Buck", phone="+31-219-23-07-78", email="facilisi@amet.co.uk")
session.add(supplier31)
supplier32 = Supplier(name="Donec Incorporated", unit_measure="100", cost_unit_per_day="191", discipline="Cash register", location="Doetinchem", times_hired="14", experience_rating="5", quality_rating="4", price_rating="5", url="http://biconical.com", contact="Illiana Norton", phone="+31-701-12-19-65", email="Cras.dolor@etultrices.co.uk")
session.add(supplier32)
supplier33 = Supplier(name="Donec Tincidunt Consulting", unit_measure="300", cost_unit_per_day="234", discipline="Food", location="Hoorn", times_hired="0", url="http://bobby.com", contact="Rhiannon Drake", phone="+31-587-69-36-10", email="Nunc@Sedeueros.edu")
session.add(supplier33)
supplier34 = Supplier(name="Dui Semper Et PC", unit_measure="550", cost_unit_per_day="315", discipline="Tents", location="Zaandam", times_hired="0", url="http://quin.com", contact="Donovan White", phone="+31-131-17-89-77", email="montes.nascetur@dui.net")
session.add(supplier34)
supplier35 = Supplier(name="Duis LLP", unit_measure="400", cost_unit_per_day="236", discipline="Tents", location="Haarlem", times_hired="46", experience_rating="3", quality_rating="4", price_rating="5", url="http://emetic.com", contact="Clinton Gilliam", phone="+31-107-82-57-48", email="Proin@Integerinmagna.net")
session.add(supplier35)
supplier36 = Supplier(name="Egestas Urna Associates", unit_measure="220", cost_unit_per_day="195", discipline="Machinery", location="Amsterdam", times_hired="0", url="http://stirlessness.com", contact="Martha Madden", phone="+31-102-26-02-19", email="luctus@mollisDuissit.ca")
session.add(supplier36)
supplier37 = Supplier(name="Eleifend Non Dapibus Corporation", unit_measure="220", cost_unit_per_day="301", discipline="Sitecrew", location="Amsterdam", times_hired="5", url="http://remarque.com", contact="Grace Calhoun", phone="+31-333-72-68-89", email="amet.consectetuer@ullamcorpermagna.net")
session.add(supplier37)
supplier38 = Supplier(name="Elementum Consulting", unit_measure="180", cost_unit_per_day="212", discipline="Plumbing", location="Amsterdam", times_hired="0", url="http://burgoyne.com", contact="Hop Shannon", phone="+31-108-21-13-83", email="tempus.eu@Pellentesqueultricies.edu")
session.add(supplier38)
supplier39 = Supplier(name="Elementum Purus Accumsan LLC", unit_measure="650", cost_unit_per_day="184", discipline="First Aid", location="Amsterdam", times_hired="1", experience_rating="5", quality_rating="5", price_rating="2", url="http://urmia.com", contact="Penelope Sears", phone="+31-491-18-68-02", email="metus@tinciduntnunc.net")
session.add(supplier39)
supplier40 = Supplier(name="Elit Nulla Facilisi Incorporated", unit_measure="150", cost_unit_per_day="222", discipline="Coins", location="Ede", times_hired="0", url="http://recontraction.com", contact="Branden Guzman", phone="+31-211-30-89-62", email="nec.ligula.consectetuer@Duis.edu")
session.add(supplier40)
supplier41 = Supplier(name="Enim Corp.", unit_measure="110", cost_unit_per_day="245", discipline="Cash register", location="Amsterdam", times_hired="5", experience_rating="5", quality_rating="5", price_rating="5", url="http://contaminous.com", contact="Isaiah Simpson", phone="+31-597-65-98-68", email="molestie.arcu.Sed@luctus.net")
session.add(supplier41)
supplier42 = Supplier(name="Enim Mi Foundation", unit_measure="250", cost_unit_per_day="293", discipline="Fencing", location="Houten", times_hired="0", url="http://petrography.com", contact="Keelie Munoz", phone="+31-870-24-00-96", email="diam.Sed@risusaultricies.net")
session.add(supplier42)
supplier43 = Supplier(name="Erat Neque Non LLP", unit_measure="300", cost_unit_per_day="186", discipline="Sitecrew", location="Nijmegen", times_hired="6", experience_rating="5", quality_rating="5", price_rating="3", url="http://vestibule.com", contact="Sheila Skinner", phone="+31-471-17-41-60", email="tincidunt.tempus.risus@utlacus.org")
session.add(supplier43)
supplier44 = Supplier(name="Et LLC", unit_measure="200", cost_unit_per_day="209", discipline="Electricity", location="Amersfoort", times_hired="0", url="http://symmetrization.com", contact="Christine Sandoval", phone="+31-158-40-98-66", email="blandit@Aliquamrutrum.com")
session.add(supplier44)
supplier45 = Supplier(name="Eu Enim Etiam Limited", unit_measure="125", cost_unit_per_day="310", discipline="Food", location="Rotterdam", times_hired="0", url="http://superrefine.com", contact="Ignacia Fitzgerald", phone="+31-646-72-39-43", email="nisl.elementum@euismodac.org")
session.add(supplier45)
supplier46 = Supplier(name="Eu Odio Incorporated", unit_measure="220", cost_unit_per_day="151", discipline="Electricity", location="Soest", times_hired="0", url="http://myogenicity.com", contact="Steven Padilla", phone="+31-840-50-30-46", email="sit.amet@ipsumdolorsit.ca")
session.add(supplier46)
supplier47 = Supplier(name="Facilisi Sed Industries", unit_measure="350", cost_unit_per_day="242", discipline="Sitecrew", location="Maastricht", times_hired="14", experience_rating="4", quality_rating="4", price_rating="3", url="http://empirical.com", contact="Jescie Arnold", phone="+31-410-62-25-16", email="sit@accumsaninterdumlibero.co.uk")
session.add(supplier47)
supplier48 = Supplier(name="Fusce Aliquam Associates", unit_measure="250", cost_unit_per_day="209", discipline="Machinery", location="Haarlem", times_hired="1", experience_rating="4", quality_rating="4", price_rating="3", url="http://hooligan.com", contact="Marsden Mcmillan", phone="+31-396-90-45-59", email="habitant.morbi@Sed.net")
session.add(supplier48)
supplier49 = Supplier(name="Habitant Consulting", unit_measure="275", cost_unit_per_day="163", discipline="Fencing", location="Baarn", times_hired="23", url="http://debeaker.com", contact="Imani Cooper", phone="+31-096-95-15-66", email="a.ultricies@dictumProin.ca")
session.add(supplier49)
supplier50 = Supplier(name="Id Libero Corporation", unit_measure="225", cost_unit_per_day="222", discipline="Food", location="Amsterdam", times_hired="0", url="http://terrier.com", contact="Mikayla Hooper", phone="+31-539-17-93-56", email="consequat.lectus.sit@sociosquadlitora.org")
session.add(supplier50)
supplier51 = Supplier(name="In Nec Orci Institute", unit_measure="175", cost_unit_per_day="245", discipline="Food", location="Amsterdam", times_hired="0", url="http://calcaria.com", contact="Galvin Coleman", phone="+31-156-67-33-12", email="id.magna.et@Donecat.ca")
session.add(supplier51)
supplier52 = Supplier(name="Ipsum Corp.", unit_measure="220", cost_unit_per_day="176", discipline="Plumbing", location="Rotterdam", times_hired="0", url="http://linebred.com", contact="Renee Jefferson", phone="+31-639-31-24-64", email="Nunc.laoreet.lectus@sagittisaugueeu.com")
session.add(supplier52)
supplier53 = Supplier(name="Lectus Pede Corporation", unit_measure="425", cost_unit_per_day="232", discipline="Tents", location="Amsterdam", times_hired="0", url="http://substriated.com", contact="Armand Macdonald", phone="+31-104-75-25-04", email="conubia@penatibuset.ca")
session.add(supplier53)
supplier54 = Supplier(name="Ligula Aenean Euismod Corporation", unit_measure="275", cost_unit_per_day="212", discipline="Sitecrew", location="Rotterdam", times_hired="0", experience_rating="5", quality_rating="5", price_rating="3", url="http://machtpolitik.com", contact="Patrick Roberts", phone="+31-365-20-66-47", email="laoreet.libero.et@Nullafacilisi.ca")
session.add(supplier54)
supplier55 = Supplier(name="Ligula Aliquam Institute", unit_measure="150", cost_unit_per_day="159", discipline="Food", location="Almere", times_hired="0", url="http://perinephrium.com", contact="Clementine Daniel", phone="+31-031-42-06-03", email="Cras@Phasellus.net")
session.add(supplier55)
supplier56 = Supplier(name="Lorem Inc.", unit_measure="200", cost_unit_per_day="315", discipline="Food", location="Rotterdam", times_hired="0", url="http://myocardia.com", contact="Alisa Kelly", phone="+31-653-16-71-32", email="quam.quis.diam@aliquet.edu")
session.add(supplier56)
supplier57 = Supplier(name="Lorem LLP", unit_measure="200", cost_unit_per_day="212", discipline="Machinery", location="Amsterdam", times_hired="14", experience_rating="5", quality_rating="5", price_rating="3", url="http://postgraduate.com", contact="Jescie Edwards", phone="+31-984-87-97-86", email="tristique.neque.venenatis@convallisdolor.org")
session.add(supplier57)
supplier58 = Supplier(name="Lorem Luctus Industries", unit_measure="250", cost_unit_per_day="314", discipline="Plumbing", location="Haarlem", times_hired="0", url="http://latreutic.com", contact="Darrel Obrien", phone="+31-287-20-96-01", email="semper@iaculislacus.com")
session.add(supplier58)
supplier59 = Supplier(name="Lorem Tristique LLP", unit_measure="120", cost_unit_per_day="271", discipline="Radios", location="Amsterdam", times_hired="7", experience_rating="5", quality_rating="5", price_rating="4", url="http://vietnamization.com", contact="Illana Evans", phone="+31-778-43-81-65", email="non.enim.Mauris@malesuada.net")
session.add(supplier59)
supplier60 = Supplier(name="Luctus Ipsum Institute", unit_measure="200", cost_unit_per_day="152", discipline="Transportation logistics", location="Amsterdam", times_hired="0", url="http://poussetting.com", contact="Scarlett Grimes", phone="+31-497-39-78-89", email="Curabitur.consequat@volutpat.net")
session.add(supplier60)
supplier61 = Supplier(name="Magna Ltd", unit_measure="300", cost_unit_per_day="258", discipline="Overnight", location="Achterveld", times_hired="0", url="http://beatty.com", contact="Sierra Wade", phone="+31-897-95-96-62", email="ac.ipsum.Phasellus@aauctornon.com")
session.add(supplier61)
supplier62 = Supplier(name="Magna Suspendisse LLC", unit_measure="200", cost_unit_per_day="168", discipline="Cash register", location="Amsterdam", times_hired="7", experience_rating="4", quality_rating="3", price_rating="5", url="http://complexity.com", contact="Calvin Sullivan", phone="+31-410-16-95-33", email="mollis.non.cursus@utlacusNulla.com")
session.add(supplier62)
supplier63 = Supplier(name="Malesuada Incorporated", unit_measure="325", cost_unit_per_day="173", discipline="Sitecrew", location="Amsterdam", times_hired="4", experience_rating="5", quality_rating="5", price_rating="3", url="http://staunch.com", contact="Delilah Ayers", phone="+31-947-39-14-33", email="adipiscing.ligula@arcu.net")
session.add(supplier63)
supplier64 = Supplier(name="Malesuada Ut Corp.", unit_measure="275", cost_unit_per_day="225", discipline="Sitecrew", location="Amsterdam", times_hired="4", experience_rating="4", quality_rating="4", price_rating="5", url="http://gayle.com", contact="Inez Meadows", phone="+31-542-56-28-24", email="ut@at.edu")
session.add(supplier64)
supplier65 = Supplier(name="Mattis Cras Incorporated", unit_measure="220", cost_unit_per_day="191", discipline="Cash register", location="Doetinchem", times_hired="8", experience_rating="4", quality_rating="5", price_rating="5", url="http://spaghetti.com", contact="Samantha Sweet", phone="+31-884-38-67-22", email="dui.augue@convallis.net")
session.add(supplier65)
supplier66 = Supplier(name="Mauris Ut Mi Institute", unit_measure="100", cost_unit_per_day="192", discipline="Cash register", location="Uden", times_hired="1", experience_rating="4", quality_rating="3", price_rating="5", url="http://closter.com", contact="Cooper Richardson", phone="+31-072-80-13-71", email="ultricies@luctusaliquetodio.org")
session.add(supplier66)
supplier67 = Supplier(name="Montes Corporation", unit_measure="150", cost_unit_per_day="245", discipline="Cash register", location="Amsterdam", times_hired="5", experience_rating="5", quality_rating="5", price_rating="5", url="http://woodiness.com", contact="Brian Hill", phone="+31-812-52-51-77", email="sociis@conubia.net")
session.add(supplier67)
supplier68 = Supplier(name="Mus Industries", unit_measure="600", cost_unit_per_day="226", discipline="Lockers", location="Nijmegen", times_hired="0", url="http://dervish.com", contact="Colton Schwartz", phone="+31-481-32-92-29", email="Praesent.eu@mifringillami.co.uk")
session.add(supplier68)
supplier69 = Supplier(name="Nec Foundation", unit_measure="100", cost_unit_per_day="308", discipline="Dispuut mee", location="Zaandam", times_hired="0", url="http://lichi.com", contact="Audrey Becker", phone="+31-126-81-99-14", email="metus.In@ridiculusmusDonec.net")
session.add(supplier69)
supplier70 = Supplier(name="Nec Metus Ltd", unit_measure="175", cost_unit_per_day="208", discipline="Cash register", location="Amsterdam", times_hired="4", experience_rating="4", quality_rating="4", price_rating="5", url="http://unsurrealistically.com", contact="Lamar Bush", phone="+31-284-60-86-28", email="ligula@orci.org")
session.add(supplier70)
supplier71 = Supplier(name="Nec Tellus Nunc PC", unit_measure="125", cost_unit_per_day="145", discipline="Cash register", location="Baarn", times_hired="3", experience_rating="1", quality_rating="1", price_rating="5", url="http://steepleless.com", contact="Timothy Harmon", phone="+31-518-39-85-17", email="tellus@Pellentesquetincidunt.net")
session.add(supplier71)
supplier72 = Supplier(name="Neque Pellentesque Massa Industries", unit_measure="625", cost_unit_per_day="204", discipline="Tents", location="Breda", times_hired="15", experience_rating="5", quality_rating="4", price_rating="3", url="http://inquisitionist.com", contact="Lara Hicks", phone="+31-363-04-05-96", email="dui.Cras@orci.org")
session.add(supplier72)
supplier73 = Supplier(name="Netus Institute", unit_measure="225", cost_unit_per_day="316", discipline="Electricity", location="Ede", times_hired="0", url="http://pilch.com", contact="Garrison Crane", phone="+31-175-36-07-55", email="egestas@arcuVestibulumut.ca")
session.add(supplier73)
supplier74 = Supplier(name="Nibh Institute", unit_measure="250", cost_unit_per_day="327", discipline="Decoration", location="Amsterdam", times_hired="0", experience_rating="5", quality_rating="5", price_rating="4", url="http://whimsey.com", contact="Martina Green", phone="+31-901-78-00-84", email="odio.sagittis.semper@ipsumSuspendissenon.net")
session.add(supplier74)
supplier75 = Supplier(name="Non Associates", unit_measure="200", cost_unit_per_day="284", discipline="Waste", location="Rotterdam", times_hired="0", url="http://profitable.com", contact="Edward Callahan", phone="+31-956-37-89-23", email="orci@ipsumportaelit.net")
session.add(supplier75)
supplier76 = Supplier(name="Non Enim Company", unit_measure="175", cost_unit_per_day="286", discipline="Sitecrew", location="Amsterdam", times_hired="2", experience_rating="5", quality_rating="5", price_rating="3", url="http://dad.com", contact="Hollee Mcmillan", phone="+31-455-44-68-08", email="penatibus.et@adipiscingligulaAenean.net")
session.add(supplier76)
supplier77 = Supplier(name="Nulla Consulting", unit_measure="180", cost_unit_per_day="264", discipline="Sitecrew", location="Amsterdam", times_hired="4", experience_rating="4", quality_rating="4", price_rating="5", url="http://gnostic.com", contact="Pascale Boyd", phone="+31-287-60-89-35", email="Phasellus.ornare@non.com")
session.add(supplier77)
supplier78 = Supplier(name="Nunc Id Enim LLP", unit_measure="225", cost_unit_per_day="244", discipline="Food", location="Hengelo", times_hired="0", url="http://outroar.com", contact="Cole Weeks", phone="+31-406-09-79-71", email="fermentum@iaculis.edu")
session.add(supplier78)
supplier79 = Supplier(name="Nunc Sed Orci Institute", unit_measure="250", cost_unit_per_day="319", discipline="Food", location="Uden", times_hired="0", url="http://macroptic.com", contact="Cullen Kramer", phone="+31-901-81-80-42", email="pretium@sagittisaugue.com")
session.add(supplier79)
supplier80 = Supplier(name="Parturient Montes LLP", unit_measure="100", cost_unit_per_day="203", discipline="Food", location="Amsterdam", times_hired="0", url="http://bursting.com", contact="Emery Melton", phone="+31-017-35-63-40", email="ipsum.cursus.vestibulum@euodiotristique.ca")
session.add(supplier80)
supplier81 = Supplier(name="Pede Malesuada Vel Limited", unit_measure="120", cost_unit_per_day="160", discipline="Food", location="Doetinchem", times_hired="0", url="http://unclimactic.com", contact="Aiko Mason", phone="+31-082-54-05-64", email="ac@etarcuimperdiet.com")
session.add(supplier81)
supplier82 = Supplier(name="Penatibus Et Incorporated", unit_measure="700", cost_unit_per_day="265", discipline="Tents", location="Amsterdam", times_hired="0", url="http://extraversively.com", contact="Hiroko Hoffman", phone="+31-849-50-34-26", email="diam@aliquamenimnec.net")
session.add(supplier82)
supplier83 = Supplier(name="Pharetra Nam LLP", unit_measure="100", cost_unit_per_day="242", discipline="Food", location="Amsterdam", times_hired="0", url="http://squeal.com", contact="Kamal Davidson", phone="+31-903-78-48-87", email="Integer@scelerisquemollisPhasellus.co.uk")
session.add(supplier83)
supplier84 = Supplier(name="Purus Mauris Limited", unit_measure="250", cost_unit_per_day="151", discipline="Food", location="Mook", times_hired="0", url="http://seductive.com", contact="Maile Foley", phone="+31-859-38-44-40", email="tempus.non.lacinia@Namconsequatdolor.edu")
session.add(supplier84)
supplier85 = Supplier(name="Quam Consulting", unit_measure="650", cost_unit_per_day="288", discipline="Producer", location="Nijmegen", times_hired="0", url="http://nonmonastic.com", contact="Lucas Hess", phone="+31-577-18-71-25", email="tempus.mauris@tellus.org")
session.add(supplier85)
supplier86 = Supplier(name="Quis Limited", unit_measure="250", cost_unit_per_day="249", discipline="Electricity", location="Rotterdam", times_hired="0", url="http://archesporium.com", contact="Felicia Robinson", phone="+31-667-07-37-76", email="In@ultrices.org")
session.add(supplier86)
supplier87 = Supplier(name="Quisque Associates", unit_measure="800", cost_unit_per_day="252", discipline="Tents", location="Sgravenhage", times_hired="3", experience_rating="4", quality_rating="4", price_rating="4", url="http://rehospitalization.com", contact="Ori Brooks", phone="+31-093-22-87-29", email="volutpat.Nulla.dignissim@aodiosemper.net")
session.add(supplier87)
supplier88 = Supplier(name="Quisque Imperdiet Consulting", unit_measure="230", cost_unit_per_day="221", discipline="Sitecrew", location="Amsterdam", times_hired="5", experience_rating="5", quality_rating="5", price_rating="3", url="http://commutability.com", contact="Aiko Calderon", phone="+31-899-55-07-61", email="gravida.nunc.sed@mattisvelit.com")
session.add(supplier88)
supplier89 = Supplier(name="Ridiculus Ltd", unit_measure="275", cost_unit_per_day="163", discipline="Food", location="Maastricht", times_hired="0", url="http://submolecule.com", contact="Dominique Mccoy", phone="+31-739-22-36-39", email="fringilla.cursus.purus@quis.net")
session.add(supplier89)
supplier90 = Supplier(name="Risus Nunc Ac Corp.", unit_measure="220", cost_unit_per_day="290", discipline="Waste", location="Amsterdam", times_hired="0", url="http://achimenes.com", contact="Tate Velez", phone="+31-658-06-53-94", email="vulputate.velit@eu.net")
session.add(supplier90)
supplier91 = Supplier(name="Rutrum Fusce Dolor Company", unit_measure="600", cost_unit_per_day="216", discipline="Tents", location="Amsterdam", times_hired="34", experience_rating="4", quality_rating="5", price_rating="3", url="http://planulate.com", contact="Cassady Jenkins", phone="+31-025-83-23-68", email="Nullam.suscipit@nonantebibendum.org")
session.add(supplier91)
supplier92 = Supplier(name="Sed Dictum Incorporated", unit_measure="150", cost_unit_per_day="273", discipline="Radios", location="Amersfoort", times_hired="0", url="http://rachises.com", contact="Declan Tate", phone="+31-941-28-89-26", email="orci@malesuada.com")
session.add(supplier92)
supplier93 = Supplier(name="Sed Hendrerit A PC", unit_measure="175", cost_unit_per_day="262", discipline="Radios", location="Amsterdam", times_hired="0", url="http://probang.com", contact="Xanthus Freeman", phone="+31-839-88-41-12", email="enim.Suspendisse@Sed.edu")
session.add(supplier93)
supplier94 = Supplier(name="Sed LLC", unit_measure="400", cost_unit_per_day="301", discipline="Signing", location="Zaandam", times_hired="0", url="http://eluvia.com", contact="Oliver Compton", phone="+31-166-34-42-03", email="ornare@pellentesqueafacilisis.org")
session.add(supplier94)
supplier95 = Supplier(name="Semper Corp.", unit_measure="650", cost_unit_per_day="208", discipline="Tents", location="Amsterdam", times_hired="9", experience_rating="5", quality_rating="3", price_rating="4", url="http://peculiarize.com", contact="Guy Merritt", phone="+31-763-29-58-82", email="dolor@lectus.co.uk")
session.add(supplier95)
supplier96 = Supplier(name="Sit Amet Company", unit_measure="175", cost_unit_per_day="211", discipline="Food", location="Edam", times_hired="0", url="http://pseudocercariae.com", contact="Scott Goff", phone="+31-267-45-70-93", email="lorem@Praesentinterdumligula.edu")
session.add(supplier96)
supplier97 = Supplier(name="Sit Amet Consectetuer Institute", unit_measure="150", cost_unit_per_day="145", discipline="Food", location="Maastricht", times_hired="0", url="http://nitrate.com", contact="Travis Underwood", phone="+31-638-40-79-55", email="ullamcorper@nasceturridiculus.edu")
session.add(supplier97)
supplier98 = Supplier(name="Sit Amet Corp.", unit_measure="200", cost_unit_per_day="267", discipline="Staff", location="Amsterdam", times_hired="0", url="http://jubilate.com", contact="Charles Joseph", phone="+31-646-66-21-34", email="nibh.Quisque.nonummy@dolor.co.uk")
session.add(supplier98)
supplier99 = Supplier(name="Sit Amet LLC", unit_measure="400", cost_unit_per_day="296", discipline="Textile prints", location="Amsterdam", times_hired="0", url="http://slipstick.com", contact="Beatrice Rodriguez", phone="+31-543-73-18-68", email="magna@tincidunt.com")
session.add(supplier99)
supplier100 = Supplier(name="Sit Industries", unit_measure="150", cost_unit_per_day="320", discipline="Sitecrew", location="Amsterdam", times_hired="3", experience_rating="5", quality_rating="5", price_rating="5", url="http://manometer.com", contact="Regan Powell", phone="+31-519-55-48-66", email="ac@metus.net")
session.add(supplier100)
supplier101 = Supplier(name="Suscipit Est Ac Institute", unit_measure="200", cost_unit_per_day="305", discipline="Food", location="Edam", times_hired="0", url="http://intarsist.com", contact="Laurel Morin", phone="+31-372-35-46-23", email="ultrices@ultrices.co.uk")
session.add(supplier101)
supplier102 = Supplier(name="Suscipit Incorporated", unit_measure="250", cost_unit_per_day="275", discipline="Decoration", location="Sgravenhage", times_hired="0", url="http://impartible.com", contact="Britanni Booker", phone="+31-422-19-65-68", email="lobortis@montesnasceturridiculus.org")
session.add(supplier102)
supplier103 = Supplier(name="Suspendisse Associates", unit_measure="200", cost_unit_per_day="178", discipline="Sitecrew", location="Amsterdam", times_hired="7", experience_rating="4", quality_rating="4", price_rating="5", url="http://venging.com", contact="Hilel Ballard", phone="+31-292-30-52-75", email="non@cursusa.org")
session.add(supplier103)
supplier104 = Supplier(name="Tincidunt Donec Vitae Incorporated", unit_measure="180", cost_unit_per_day="195", discipline="Waste", location="Ermelo", times_hired="0", url="http://hysteresis.com", contact="Indigo Sosa", phone="+31-209-10-12-51", email="dapibus.rutrum.justo@disparturientmontes.ca")
session.add(supplier104)
supplier105 = Supplier(name="Ullamcorper Corp.", unit_measure="300", cost_unit_per_day="229", discipline="Plumbing", location="Amsterdam", times_hired="0", url="http://ibis.com", contact="Murphy Duffy", phone="+31-463-12-08-80", email="aliquam.iaculis.lacus@turpisvitae.com")
session.add(supplier105)
supplier106 = Supplier(name="Ultrices Industries", unit_measure="275", cost_unit_per_day="166", discipline="Electricity", location="Amsterdam", times_hired="0", url="http://unmanual.com", contact="Jamalia Holt", phone="+31-340-28-32-38", email="urna@Etiamgravidamolestie.ca")
session.add(supplier106)
supplier107 = Supplier(name="Urna Ut Corp.", unit_measure="225", cost_unit_per_day="237", discipline="Food", location="Haarlem", times_hired="0", url="http://misalleging.com", contact="Cooper Finley", phone="+31-760-63-80-81", email="Integer.sem.elit@atvelitPellentesque.net")
session.add(supplier107)
supplier108 = Supplier(name="Ut Associates", unit_measure="175", cost_unit_per_day="250", discipline="Food", location="Amsterdam", times_hired="0", url="http://fishable.com", contact="Dominique Dunlap", phone="+31-851-99-10-12", email="Duis.cursus.diam@velpede.edu")
session.add(supplier108)
supplier109 = Supplier(name="Ut Company", unit_measure="650", cost_unit_per_day="252", discipline="First Aid", location="Nijmegen", times_hired="35", experience_rating="5", quality_rating="4", price_rating="5", url="http://loanshift.com", contact="Reed Mullins", phone="+31-903-51-61-97", email="risus.Quisque@tristique.edu")
session.add(supplier109)
supplier110 = Supplier(name="Vel Mauris Integer Foundation", unit_measure="150", cost_unit_per_day="183", discipline="Food", location="Amsterdam", times_hired="0", url="http://jormungandr.com", contact="Hakeem Le", phone="+31-731-82-84-86", email="lectus@luctusaliquetodio.org")
session.add(supplier110)
supplier111 = Supplier(name="Vel Mauris Integer Ltd", unit_measure="200", cost_unit_per_day="301", discipline="Food", location="Nijmegen", times_hired="0", url="http://unbarricade.com", contact="Elmo Lopez", phone="+31-589-96-55-12", email="ut.quam.vel@massaMauris.com")
session.add(supplier111)
supplier112 = Supplier(name="Venenatis A Magna Limited", unit_measure="225", cost_unit_per_day="311", discipline="Food", location="Soest", times_hired="0", url="http://subtutorship.com", contact="Rooney Wiley", phone="+31-725-32-39-60", email="sociis.natoque.penatibus@Nuncullamcorpervelit.edu")
session.add(supplier112)
supplier113 = Supplier(name="Venenatis Lacus Etiam LLC", unit_measure="100", cost_unit_per_day="294", discipline="Food", location="Soest", times_hired="0", url="http://intumescency.com", contact="Jakeem Houston", phone="+31-437-33-45-51", email="metus@Integeraliquam.ca")
session.add(supplier113)



session.commit()
